//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.AlumniService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumniDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniWCF.DTO")]
    [System.SerializableAttribute()]
    public partial class AlumniDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] DegreesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] DistrictsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] FacultiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GraduationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MajorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] MajorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.Mvc.SelectListItem[] StatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree {
            get {
                return this.DegreeField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreeField, value) != true)) {
                    this.DegreeField = value;
                    this.RaisePropertyChanged("Degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Degrees {
            get {
                return this.DegreesField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreesField, value) != true)) {
                    this.DegreesField = value;
                    this.RaisePropertyChanged("Degrees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Districts {
            get {
                return this.DistrictsField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictsField, value) != true)) {
                    this.DistrictsField = value;
                    this.RaisePropertyChanged("Districts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Faculties {
            get {
                return this.FacultiesField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultiesField, value) != true)) {
                    this.FacultiesField = value;
                    this.RaisePropertyChanged("Faculties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultyID {
            get {
                return this.FacultyIDField;
            }
            set {
                if ((this.FacultyIDField.Equals(value) != true)) {
                    this.FacultyIDField = value;
                    this.RaisePropertyChanged("FacultyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullAddress {
            get {
                return this.FullAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FullAddressField, value) != true)) {
                    this.FullAddressField = value;
                    this.RaisePropertyChanged("FullAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GraduationYear {
            get {
                return this.GraduationYearField;
            }
            set {
                if ((this.GraduationYearField.Equals(value) != true)) {
                    this.GraduationYearField = value;
                    this.RaisePropertyChanged("GraduationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInProfile {
            get {
                return this.LinkedInProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInProfileField, value) != true)) {
                    this.LinkedInProfileField = value;
                    this.RaisePropertyChanged("LinkedInProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MajorID {
            get {
                return this.MajorIDField;
            }
            set {
                if ((this.MajorIDField.Equals(value) != true)) {
                    this.MajorIDField = value;
                    this.RaisePropertyChanged("MajorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorName {
            get {
                return this.MajorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorNameField, value) != true)) {
                    this.MajorNameField = value;
                    this.RaisePropertyChanged("MajorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] Majors {
            get {
                return this.MajorsField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorsField, value) != true)) {
                    this.MajorsField = value;
                    this.RaisePropertyChanged("Majors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.Mvc.SelectListItem[] States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumniService.IAlumniServices")]
    public interface IAlumniServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetAlumnis", ReplyAction="http://tempuri.org/IAlumniServices/GetAlumnisResponse")]
        AlumniManagement.AlumniService.AlumniDTO[] GetAlumnis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetAlumnis", ReplyAction="http://tempuri.org/IAlumniServices/GetAlumnisResponse")]
        System.Threading.Tasks.Task<AlumniManagement.AlumniService.AlumniDTO[]> GetAlumnisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetAlumniByID", ReplyAction="http://tempuri.org/IAlumniServices/GetAlumniByIDResponse")]
        AlumniManagement.AlumniService.AlumniDTO GetAlumniByID(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetAlumniByID", ReplyAction="http://tempuri.org/IAlumniServices/GetAlumniByIDResponse")]
        System.Threading.Tasks.Task<AlumniManagement.AlumniService.AlumniDTO> GetAlumniByIDAsync(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetAlumniFullName", ReplyAction="http://tempuri.org/IAlumniServices/GetAlumniFullNameResponse")]
        AlumniManagement.AlumniService.AlumniDTO[] GetAlumniFullName(string fullName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetAlumniFullName", ReplyAction="http://tempuri.org/IAlumniServices/GetAlumniFullNameResponse")]
        System.Threading.Tasks.Task<AlumniManagement.AlumniService.AlumniDTO[]> GetAlumniFullNameAsync(string fullName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/AddAlumni", ReplyAction="http://tempuri.org/IAlumniServices/AddAlumniResponse")]
        void AddAlumni(AlumniManagement.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/AddAlumni", ReplyAction="http://tempuri.org/IAlumniServices/AddAlumniResponse")]
        System.Threading.Tasks.Task AddAlumniAsync(AlumniManagement.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/UpdateAlumni", ReplyAction="http://tempuri.org/IAlumniServices/UpdateAlumniResponse")]
        void UpdateAlumni(AlumniManagement.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/UpdateAlumni", ReplyAction="http://tempuri.org/IAlumniServices/UpdateAlumniResponse")]
        System.Threading.Tasks.Task UpdateAlumniAsync(AlumniManagement.AlumniService.AlumniDTO alumni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/DeleteAlumni", ReplyAction="http://tempuri.org/IAlumniServices/DeleteAlumniResponse")]
        void DeleteAlumni(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/DeleteAlumni", ReplyAction="http://tempuri.org/IAlumniServices/DeleteAlumniResponse")]
        System.Threading.Tasks.Task DeleteAlumniAsync(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetDistrictIdByName", ReplyAction="http://tempuri.org/IAlumniServices/GetDistrictIdByNameResponse")]
        int GetDistrictIdByName(string districtName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetDistrictIdByName", ReplyAction="http://tempuri.org/IAlumniServices/GetDistrictIdByNameResponse")]
        System.Threading.Tasks.Task<int> GetDistrictIdByNameAsync(string districtName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetStateIdByName", ReplyAction="http://tempuri.org/IAlumniServices/GetStateIdByNameResponse")]
        int GetStateIdByName(string stateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/GetStateIdByName", ReplyAction="http://tempuri.org/IAlumniServices/GetStateIdByNameResponse")]
        System.Threading.Tasks.Task<int> GetStateIdByNameAsync(string stateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/ImportFromExcel", ReplyAction="http://tempuri.org/IAlumniServices/ImportFromExcelResponse")]
        void ImportFromExcel(AlumniManagement.AlumniService.AlumniDTO alumniDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumniServices/ImportFromExcel", ReplyAction="http://tempuri.org/IAlumniServices/ImportFromExcelResponse")]
        System.Threading.Tasks.Task ImportFromExcelAsync(AlumniManagement.AlumniService.AlumniDTO alumniDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumniServicesChannel : AlumniManagement.AlumniService.IAlumniServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumniServicesClient : System.ServiceModel.ClientBase<AlumniManagement.AlumniService.IAlumniServices>, AlumniManagement.AlumniService.IAlumniServices {
        
        public AlumniServicesClient() {
        }
        
        public AlumniServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumniServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumniServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.AlumniService.AlumniDTO[] GetAlumnis() {
            return base.Channel.GetAlumnis();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.AlumniService.AlumniDTO[]> GetAlumnisAsync() {
            return base.Channel.GetAlumnisAsync();
        }
        
        public AlumniManagement.AlumniService.AlumniDTO GetAlumniByID(int alumniID) {
            return base.Channel.GetAlumniByID(alumniID);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.AlumniService.AlumniDTO> GetAlumniByIDAsync(int alumniID) {
            return base.Channel.GetAlumniByIDAsync(alumniID);
        }
        
        public AlumniManagement.AlumniService.AlumniDTO[] GetAlumniFullName(string fullName) {
            return base.Channel.GetAlumniFullName(fullName);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.AlumniService.AlumniDTO[]> GetAlumniFullNameAsync(string fullName) {
            return base.Channel.GetAlumniFullNameAsync(fullName);
        }
        
        public void AddAlumni(AlumniManagement.AlumniService.AlumniDTO alumni) {
            base.Channel.AddAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task AddAlumniAsync(AlumniManagement.AlumniService.AlumniDTO alumni) {
            return base.Channel.AddAlumniAsync(alumni);
        }
        
        public void UpdateAlumni(AlumniManagement.AlumniService.AlumniDTO alumni) {
            base.Channel.UpdateAlumni(alumni);
        }
        
        public System.Threading.Tasks.Task UpdateAlumniAsync(AlumniManagement.AlumniService.AlumniDTO alumni) {
            return base.Channel.UpdateAlumniAsync(alumni);
        }
        
        public void DeleteAlumni(int alumniID) {
            base.Channel.DeleteAlumni(alumniID);
        }
        
        public System.Threading.Tasks.Task DeleteAlumniAsync(int alumniID) {
            return base.Channel.DeleteAlumniAsync(alumniID);
        }
        
        public int GetDistrictIdByName(string districtName) {
            return base.Channel.GetDistrictIdByName(districtName);
        }
        
        public System.Threading.Tasks.Task<int> GetDistrictIdByNameAsync(string districtName) {
            return base.Channel.GetDistrictIdByNameAsync(districtName);
        }
        
        public int GetStateIdByName(string stateName) {
            return base.Channel.GetStateIdByName(stateName);
        }
        
        public System.Threading.Tasks.Task<int> GetStateIdByNameAsync(string stateName) {
            return base.Channel.GetStateIdByNameAsync(stateName);
        }
        
        public void ImportFromExcel(AlumniManagement.AlumniService.AlumniDTO alumniDTO) {
            base.Channel.ImportFromExcel(alumniDTO);
        }
        
        public System.Threading.Tasks.Task ImportFromExcelAsync(AlumniManagement.AlumniService.AlumniDTO alumniDTO) {
            return base.Channel.ImportFromExcelAsync(alumniDTO);
        }
    }
}
