//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.FacultyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniWCF.DTO")]
    [System.SerializableAttribute()]
    public partial class FacultyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultyID {
            get {
                return this.FacultyIDField;
            }
            set {
                if ((this.FacultyIDField.Equals(value) != true)) {
                    this.FacultyIDField = value;
                    this.RaisePropertyChanged("FacultyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyName {
            get {
                return this.FacultyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNameField, value) != true)) {
                    this.FacultyNameField = value;
                    this.RaisePropertyChanged("FacultyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacultyService.IFacultyServices")]
    public interface IFacultyServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/GetFaculties", ReplyAction="http://tempuri.org/IFacultyServices/GetFacultiesResponse")]
        AlumniManagement.FacultyService.FacultyDTO[] GetFaculties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/GetFaculties", ReplyAction="http://tempuri.org/IFacultyServices/GetFacultiesResponse")]
        System.Threading.Tasks.Task<AlumniManagement.FacultyService.FacultyDTO[]> GetFacultiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/GetFacultyByID", ReplyAction="http://tempuri.org/IFacultyServices/GetFacultyByIDResponse")]
        AlumniManagement.FacultyService.FacultyDTO GetFacultyByID(int facultyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/GetFacultyByID", ReplyAction="http://tempuri.org/IFacultyServices/GetFacultyByIDResponse")]
        System.Threading.Tasks.Task<AlumniManagement.FacultyService.FacultyDTO> GetFacultyByIDAsync(int facultyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/GetFacultyIdByName", ReplyAction="http://tempuri.org/IFacultyServices/GetFacultyIdByNameResponse")]
        AlumniManagement.FacultyService.FacultyDTO GetFacultyIdByName(string facultyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/GetFacultyIdByName", ReplyAction="http://tempuri.org/IFacultyServices/GetFacultyIdByNameResponse")]
        System.Threading.Tasks.Task<AlumniManagement.FacultyService.FacultyDTO> GetFacultyIdByNameAsync(string facultyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/AddFaculty", ReplyAction="http://tempuri.org/IFacultyServices/AddFacultyResponse")]
        void AddFaculty(AlumniManagement.FacultyService.FacultyDTO faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/AddFaculty", ReplyAction="http://tempuri.org/IFacultyServices/AddFacultyResponse")]
        System.Threading.Tasks.Task AddFacultyAsync(AlumniManagement.FacultyService.FacultyDTO faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/UpdateFaculty", ReplyAction="http://tempuri.org/IFacultyServices/UpdateFacultyResponse")]
        void UpdateFaculty(AlumniManagement.FacultyService.FacultyDTO faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/UpdateFaculty", ReplyAction="http://tempuri.org/IFacultyServices/UpdateFacultyResponse")]
        System.Threading.Tasks.Task UpdateFacultyAsync(AlumniManagement.FacultyService.FacultyDTO faculty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/DeleteFaculty", ReplyAction="http://tempuri.org/IFacultyServices/DeleteFacultyResponse")]
        void DeleteFaculty(int facultyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacultyServices/DeleteFaculty", ReplyAction="http://tempuri.org/IFacultyServices/DeleteFacultyResponse")]
        System.Threading.Tasks.Task DeleteFacultyAsync(int facultyID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacultyServicesChannel : AlumniManagement.FacultyService.IFacultyServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacultyServicesClient : System.ServiceModel.ClientBase<AlumniManagement.FacultyService.IFacultyServices>, AlumniManagement.FacultyService.IFacultyServices {
        
        public FacultyServicesClient() {
        }
        
        public FacultyServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacultyServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultyServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultyServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.FacultyService.FacultyDTO[] GetFaculties() {
            return base.Channel.GetFaculties();
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.FacultyService.FacultyDTO[]> GetFacultiesAsync() {
            return base.Channel.GetFacultiesAsync();
        }
        
        public AlumniManagement.FacultyService.FacultyDTO GetFacultyByID(int facultyID) {
            return base.Channel.GetFacultyByID(facultyID);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.FacultyService.FacultyDTO> GetFacultyByIDAsync(int facultyID) {
            return base.Channel.GetFacultyByIDAsync(facultyID);
        }
        
        public AlumniManagement.FacultyService.FacultyDTO GetFacultyIdByName(string facultyName) {
            return base.Channel.GetFacultyIdByName(facultyName);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.FacultyService.FacultyDTO> GetFacultyIdByNameAsync(string facultyName) {
            return base.Channel.GetFacultyIdByNameAsync(facultyName);
        }
        
        public void AddFaculty(AlumniManagement.FacultyService.FacultyDTO faculty) {
            base.Channel.AddFaculty(faculty);
        }
        
        public System.Threading.Tasks.Task AddFacultyAsync(AlumniManagement.FacultyService.FacultyDTO faculty) {
            return base.Channel.AddFacultyAsync(faculty);
        }
        
        public void UpdateFaculty(AlumniManagement.FacultyService.FacultyDTO faculty) {
            base.Channel.UpdateFaculty(faculty);
        }
        
        public System.Threading.Tasks.Task UpdateFacultyAsync(AlumniManagement.FacultyService.FacultyDTO faculty) {
            return base.Channel.UpdateFacultyAsync(faculty);
        }
        
        public void DeleteFaculty(int facultyID) {
            base.Channel.DeleteFaculty(facultyID);
        }
        
        public System.Threading.Tasks.Task DeleteFacultyAsync(int facultyID) {
            return base.Channel.DeleteFacultyAsync(facultyID);
        }
    }
}
