//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniManagement.JobHistoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobHistoryDTO", Namespace="http://schemas.datacontract.org/2004/07/AlumniWCF.DTO")]
    [System.SerializableAttribute()]
    public partial class JobHistoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlumniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlumniIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobHistoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alumni {
            get {
                return this.AlumniField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumniField, value) != true)) {
                    this.AlumniField = value;
                    this.RaisePropertyChanged("Alumni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlumniID {
            get {
                return this.AlumniIDField;
            }
            set {
                if ((this.AlumniIDField.Equals(value) != true)) {
                    this.AlumniIDField = value;
                    this.RaisePropertyChanged("AlumniID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobHistoryID {
            get {
                return this.JobHistoryIDField;
            }
            set {
                if ((this.JobHistoryIDField.Equals(value) != true)) {
                    this.JobHistoryIDField = value;
                    this.RaisePropertyChanged("JobHistoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobHistoryService.IJobHistoryServices")]
    public interface IJobHistoryServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/GetJobHistories", ReplyAction="http://tempuri.org/IJobHistoryServices/GetJobHistoriesResponse")]
        AlumniManagement.JobHistoryService.JobHistoryDTO[] GetJobHistories(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/GetJobHistories", ReplyAction="http://tempuri.org/IJobHistoryServices/GetJobHistoriesResponse")]
        System.Threading.Tasks.Task<AlumniManagement.JobHistoryService.JobHistoryDTO[]> GetJobHistoriesAsync(int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/GetJobHistoryByID", ReplyAction="http://tempuri.org/IJobHistoryServices/GetJobHistoryByIDResponse")]
        AlumniManagement.JobHistoryService.JobHistoryDTO GetJobHistoryByID(int alumniID, int jobHistoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/GetJobHistoryByID", ReplyAction="http://tempuri.org/IJobHistoryServices/GetJobHistoryByIDResponse")]
        System.Threading.Tasks.Task<AlumniManagement.JobHistoryService.JobHistoryDTO> GetJobHistoryByIDAsync(int alumniID, int jobHistoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/AddJobHistory", ReplyAction="http://tempuri.org/IJobHistoryServices/AddJobHistoryResponse")]
        void AddJobHistory(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/AddJobHistory", ReplyAction="http://tempuri.org/IJobHistoryServices/AddJobHistoryResponse")]
        System.Threading.Tasks.Task AddJobHistoryAsync(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/UpdateJobHistory", ReplyAction="http://tempuri.org/IJobHistoryServices/UpdateJobHistoryResponse")]
        void UpdateJobHistory(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/UpdateJobHistory", ReplyAction="http://tempuri.org/IJobHistoryServices/UpdateJobHistoryResponse")]
        System.Threading.Tasks.Task UpdateJobHistoryAsync(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/DeleteJobHistory", ReplyAction="http://tempuri.org/IJobHistoryServices/DeleteJobHistoryResponse")]
        void DeleteJobHistory(int jobHistoryID, int alumniID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobHistoryServices/DeleteJobHistory", ReplyAction="http://tempuri.org/IJobHistoryServices/DeleteJobHistoryResponse")]
        System.Threading.Tasks.Task DeleteJobHistoryAsync(int jobHistoryID, int alumniID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobHistoryServicesChannel : AlumniManagement.JobHistoryService.IJobHistoryServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobHistoryServicesClient : System.ServiceModel.ClientBase<AlumniManagement.JobHistoryService.IJobHistoryServices>, AlumniManagement.JobHistoryService.IJobHistoryServices {
        
        public JobHistoryServicesClient() {
        }
        
        public JobHistoryServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobHistoryServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobHistoryServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobHistoryServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlumniManagement.JobHistoryService.JobHistoryDTO[] GetJobHistories(int alumniID) {
            return base.Channel.GetJobHistories(alumniID);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.JobHistoryService.JobHistoryDTO[]> GetJobHistoriesAsync(int alumniID) {
            return base.Channel.GetJobHistoriesAsync(alumniID);
        }
        
        public AlumniManagement.JobHistoryService.JobHistoryDTO GetJobHistoryByID(int alumniID, int jobHistoryID) {
            return base.Channel.GetJobHistoryByID(alumniID, jobHistoryID);
        }
        
        public System.Threading.Tasks.Task<AlumniManagement.JobHistoryService.JobHistoryDTO> GetJobHistoryByIDAsync(int alumniID, int jobHistoryID) {
            return base.Channel.GetJobHistoryByIDAsync(alumniID, jobHistoryID);
        }
        
        public void AddJobHistory(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID) {
            base.Channel.AddJobHistory(jobHistory, alumniID);
        }
        
        public System.Threading.Tasks.Task AddJobHistoryAsync(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID) {
            return base.Channel.AddJobHistoryAsync(jobHistory, alumniID);
        }
        
        public void UpdateJobHistory(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID) {
            base.Channel.UpdateJobHistory(jobHistory, alumniID);
        }
        
        public System.Threading.Tasks.Task UpdateJobHistoryAsync(AlumniManagement.JobHistoryService.JobHistoryDTO jobHistory, int alumniID) {
            return base.Channel.UpdateJobHistoryAsync(jobHistory, alumniID);
        }
        
        public void DeleteJobHistory(int jobHistoryID, int alumniID) {
            base.Channel.DeleteJobHistory(jobHistoryID, alumniID);
        }
        
        public System.Threading.Tasks.Task DeleteJobHistoryAsync(int jobHistoryID, int alumniID) {
            return base.Channel.DeleteJobHistoryAsync(jobHistoryID, alumniID);
        }
    }
}
